---
name: "Test (CI)"

on:
  push:
    branches: ["main", "master", "workflows-update"]
  pull_request:
    # The branches below must be a subset of the branches above:
    branches: ["main", "master", "workflows-update"]

jobs:
  test-with-npm:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        buildtype:
          - dev
          - prod
    continue-on-error: true
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '16'
      - name: Package install
        run: npm install
      - name: Package build
        run: npm run build:${{ matrix.buildtype }}
      - name: Package test
        run: npm run test
      - name: Package lint
        run: npm run lint
  test-with-yarn:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '16'
      - name: Package install
        run: yarn install
      - name: Package build
        run: yarn
      - name: Package test
        run: yarn check
      - name: Package audit
        run: yarn audit || yarn run lint
